# Generated by Django 4.2.29 on 2026-03-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ley',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=100)),
                ('archivo', models.FileField(upload_to='leyes/')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
