# Generated by Django 4.2.29 on 2026-03-22 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ley',
            name='fecha',
        ),
    ]
