# Generated by Django 4.2.29 on 2026-03-20 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Audiencia',
        ),
        migrations.DeleteModel(
            name='Recordatorio',
        ),
        migrations.AddField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='dpi',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
