# Generated by Django 4.2.29 on 2026-03-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiencia',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='audiencia',
            name='tipo',
        ),
        migrations.AddField(
            model_name='audiencia',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='audiencia',
            name='dpi',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='audiencia',
            name='estado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='audiencia',
            name='expediente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='audiencia',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audiencia',
            name='tipo_caso',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='audiencia',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audiencia',
            name='juzgado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='audiencia',
            name='proceso',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
