# Generated by Django 6.0.3 on 2026-03-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(default='Guatemala', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='dpi',
            field=models.CharField(default='0000000000000', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.CharField(default='Activo', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_audiencia',
            field=models.DateTimeField(null=True,blank=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='juzgado',
            field=models.CharField(default='pendiente', max_length=200),
            preserve_default=False,
        ),
    ]
