# Generated by Django 4.2.29 on 2026-03-22 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_remove_audiencia_descripcion_remove_audiencia_tipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expediente',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='expediente',
            name='juzgado',
        ),
        migrations.RemoveField(
            model_name='expediente',
            name='proceso',
        ),
        migrations.AddField(
            model_name='expediente',
            name='archivo',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expediente',
            name='estado',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expediente',
            name='gaveta',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expediente',
            name='numero',
            field=models.CharField(max_length=100),
        ),
    ]
