# Generated by Django 4.2.29 on 2026-03-15 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_direccion_cliente_dpi_cliente_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='expediente',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_audiencia',
            field=models.DateTimeField(default='2026-03-16 10:00'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_expediente', models.CharField(max_length=100)),
                ('tipo_proceso', models.CharField(max_length=200)),
                ('juzgado', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
        ),
    ]
