# Generated by Django 4.2.29 on 2026-03-20 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_audiencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='dpi',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
