# Generated by Django 4.2.29 on 2026-03-20 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_cliente_dpi'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiencia',
            name='proceso',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audiencia',
            name='tipo',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
