# Generated by Django 4.2.29 on 2026-03-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_recordatorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiencia',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
