# Generated by Django 4.2.29 on 2026-03-17 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_alter_audiencia_observaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expediente',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='recordatorio',
            name='audiencia',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='estado',
            new_name='expediente',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='dpi',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_audiencia',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='juzgado',
        ),
        migrations.DeleteModel(
            name='Audiencia',
        ),
        migrations.DeleteModel(
            name='Expediente',
        ),
        migrations.DeleteModel(
            name='Recordatorio',
        ),
    ]
