# Generated by Django 4.2.29 on 2026-03-17 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_remove_cliente_expediente_expediente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('juzgado', models.CharField(max_length=200)),
                ('tipo_audiencia', models.CharField(max_length=200)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.expediente')),
            ],
        ),
    ]
