# Generated by Django 4.2.29 on 2026-03-17 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_audiencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recordatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_antes', models.IntegerField()),
                ('enviado', models.BooleanField(default=False)),
                ('audiencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.audiencia')),
            ],
        ),
    ]
